### PR TITLE
Add explanations and format as sections

### PR DESCRIPTION
**Pull request by koppor**
The [adr-tools](https://github.com/npryce/adr-tools) offer a [markdown template](https://github.com/npryce/adr-tools/blob/master/src/template.md) which uses sections.
In the text of this template, the word "sections" is also used.

So, I converted the single-line items into sections and kept the questions.

I used `<...>` to indicate place holders. This seems the common notation in Markdown files.

### CODE REVIEW

**Comment by joelparkerhenderson** [comment]
Thanks for the PR. I understand your goal and like it.

Can you please proofread this by viewing the .md file in GitHub so you can fix the formatting errors.

**Comment by koppor** [comment]
Here a screenshot of the rendered markdown:

grafik

I know that the last line is missing, but I cannot see why it is missing. I think, this placeholders will be replaced. Alternatively, I could replace `<...>` by something else or just remove `<` and `>` everywhere. I wanted to indicate placeholders.

What other formatting issues do you see? 😇

**Comment by koppor** [comment]
Bump. 😇

**Comment by joelparkerhenderson** [comment]
Good thanks! (And this is a really long-time coming-- thank you for your patience and continuing improvements!)

**Pull request merged**
